### ISSUE TITLE
asset-name configuration is not sent back to Mondoo Platform

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/packer-plugin-cnspec#137]
**Describe the bug**
When the cnspec provisioner is connected to Mondoo Platform, the `asset-name` configuration is not sent back correctly to Mondoo Platform. 

![image](https://github.com/mondoohq/packer-plugin-cnspec/assets/49754039/4226f3c7-e913-43a9-a35f-afe4d45166c2)

**To Reproduce**

In the packer build template add the following configuration ...

```
  provisioner "cnspec" {
    on_failure = "continue"
    asset_name = "test-name"
    sudo {
      active = true
    }
    annotations = {
      Source_AMI    = "Foo"
      Creation_Date = "Bar"
    }
  }
}
```

**Expected behavior**

**Screenshots or CLI Output**
If applicable, add screenshots or the CLI output to help explain your problem.

**Desktop (please complete the following information):**

- OS: [e.g. macOS]
- OS Version: [e.g. 13.0]
- Browser if applicable: [e.g. Chrome, Firefox]
- Browser Version: [e.g. 106]

**Additional context**

**Comment by chris-rock** [comment]
probably related to https://github.com/mondoohq/cnquery/pull/2282 and should be fixed with the next cnspec release
