### ISSUE TITLE
plugin cannot gather the full report

### ISSUE THREAD

**Issue by czunker** [mondoohq/packer-plugin-cnspec#149]
**Describe the bug**
Different error messages while running the plugin:
```
failed to handshake
```

```
could not gather the full report
```

**To Reproduce**

2. Select '....'
4. Note the error

**Expected behavior**
This shouldn't error.

**Desktop (please complete the following information):**

- packer-plugin-cnspec v9.2.4

**Additional context**
It works with packer-plugin-cnspec v9.2.2.

**Comment by czunker** [comment]
It is the combination of cnspec verison and os provider version. Downgrading to os provider 9.0.16 causes the error.

Upgrading the os provider fixes it again.

**Comment by vjeffrey** [comment]
can we close this? sounds like its not a problem with the latest os provider?

**Comment by czunker** [comment]
> can we close this? sounds like its not a problem with the latest os provider?

Yes and no.
In case you only use the packer plugin, it can be a problem with the cnspec os provider, because the packer pugin does not automatically update the cnspec os provider. So, in cases where you use the packer plugin and have an os provider < 9.1.0, it fails. Updating the provider on plugin start (#150 ) solves it.
