### ISSUE TITLE
Plugin versions & Packer 1.11.0

### ISSUE THREAD

**Issue by lbajolet-hashicorp** [mondoohq/packer-plugin-cnspec#208]
Hi there!

I'm one of the Packer core developers, and I'm opening this issue to let you know of the upcoming changes to Packer, specifically with v1.11.0 (tentatively scheduled for an April release), namely we're changing how plugins are discovered and loaded.
We're officialising pre-release support for our tooling, we've settled on suporting `-dev` versions only to keep the logic simple, any other pre-release (e.g. `-alpha1`, `-beta1`, etc.) will be rejected by Packer.

With this change, we're also being a bit more strict on the plugins we report and load. Namely we're mandating SHA256SUM files alongside the binary, and versions need to be coherent between the file name, and the version reported by describe.

This last point is one we noticed will be a problem for your plugin.

I attempted to install the latest version of the plugin earlier today, and noticed that they're published under `10.7.3-dev`, although they're a final version.
Our changes make it impossible for Packer to load the plugin, as its reported version will be different from the one it's named with.

To be transparent with you, this is something we'll probably change slightly between now and the final release: today the behaviour is that installation works, and loading doesn't, and by the time we release, we'll add a check that the version installed is indeed what is indicated by the origin.

While looking at the Makefile for the plugin to try and adapt it to work with our updated workflow, we also noticed that the version produced by the Makefile's build/dev targets has metadata in the version radical, to which a prerelease is appended if it exists.

This is technically valid semver, however the specification mandates that the metadata appears as the final information, after the version and pre-release status. The version that is produced by the Makefile will look like `10.7.1+161-dev`, which ends-up being recognised as a release version, since the pre-release is amalgamated with the added metadata.
To contrast, a pre-release version with metadata should be of the following form: `10.7.1-dev+161`.

In order for the plugin to smoothly be supported when v1.11.0 of Packer is released, I suggest doing the following:

1. Remove the `PreRelease` value of `dev` in the branch when releasing: this will make sure the final binary is not marked as a pre-release, and that Packer will be able to install, discover and load the plugin when necessary.
2. Change how the `VERSION` is computed in the Makefile: I suggest keeping the version simple, by only exposing the radical of the version, i.e. `10.7.3`
3. If metadata are important to you, I suggest adding them to the `VersionPrerelease` during the dev build: adding a value with that metadata for `dev` builds will make it semver compliant, and Packer will be able to load it as a pre-release.

Regarding my first suggestion, I believe this might also be done during the release build. I believe our plugins change the value of `VersionPrerelease` to be empty when building it through some `ldflags`.

Please let me know if those suggestions make sense to you.
I'm also disposed to open a PR for applying those suggestions if you think they make sense.

PS: For information and testing, we have released a [blog post](https://www.hashicorp.com/blog/predictable-plugin-loading-in-packer-1-11) recently to explain the changes coming up to Packer, and we've also released [Packer v1.11.0-alpha](https://releases.hashicorp.com/packer/1.11.0-alpha/) with which you can test your plugin.

**Comment by chris-rock** [comment]
@lbajolet-hashicorp thank you very much for the update. We do not use -dev versions right now, can you point out where this is used and where you see the dev version. Its not on github and I do not see it on https://developer.hashicorp.com/packer/integrations/mondoohq/cnspec either.

**Comment by lbajolet-hashicorp** [comment]
Hi @chris-rock,

Regarding the `-dev` suffix for the version, this is in the `version/version.go` file line 21, the `VersionPrerelease = "dev"`.

This is not in the release name on Github afaik, nor is it in the docs, since they're signalled on release, so unless the tag has a pre-release to its name, it will not be included. However the plugin reports its version as `-dev` if the `VersionPrerelease` is not empty when released.

For example if you get the binary for the plugin from one of the releases (either manually or through commands like `packer plugins install`/`packer init`), and run the `describe` command on it, you will see the version being reported with a pre-release:

```sh
$ ~/.packer.d/plugins/github.com/mondoohq/cnspec/packer-plugin-cnspec_v10.7.3_x5.0_linux_amd64 describe 2>/dev/null
{"version":"10.7.3-dev","sdk_version":"0.5.2","api_version":"x5.0","builders":[],"post_processors":[],"provisioners":["-packer-default-plugin-name-"],"datasources":[]}
```

**Comment by chris-rock** [comment]
Thank you for the hint @lbajolet-hashicorp We are releasing a version with dev flag removed.
