### ISSUE TITLE
Assets being overwritten. What determines unique Assets?

### ISSUE THREAD

**Issue by Beeez** [mondoohq/packer-plugin-cnspec#242]
**Describe the bug**
Assets in Mondoo Inventory are being overwritten each time I run a build. I am setting asset_name uniquely, and my assumption is that assets are identified based off of the asset name? 

**To Reproduce**
1. Create a Packer file (similar setup to these packer examples: https://github.com/vmware-samples/packer-examples-for-vsphere/blob/develop/builds/windows/server/2022/windows-server.pkr.hcl) 
2. Add cnspec provisioner, setting `asset_name` to the vm name + `build_date`
3. Run build for Windows Server 2022 Datacenter. Asset shows up in Mondoo Console as `packer-updated-windows-server-2022-datacenter-2024-04-30 14:27 UTC`
4.  Run build for Windows Server 2019 Datacenter. Asset shows up in Mondoo Console as `packer-updated-windows-server-2019-datacenter-2024-04-30 14:38 UTC`. This asset has the same inventory ID in the URL of the console. The 2022 one is overwritten

```
locals {
build_date                 = formatdate("YYYY-MM-DD hh:mm ZZZ", timestamp())

...

vm_name_datacenter_updated      = "packer-updated-${var.vm_guest_os_family}-${var.vm_guest_os_name}-${var.vm_guest_os_version}-${var.vm_guest_os_edition_datacenter}"

}

...

build {
  provisioner "cnspec" {
    only = ["vsphere-clone.windows-server-datacenter-update"]
    winrm_user         = var.build_username
    winrm_password     = var.build_password
    asset_name         = "${local.vm_name_datacenter_updated}-${local.build_date}"
    host_alias         = "${local.vm_name_datacenter_updated}-${local.build_date}"
    on_failure         = "continue"
    score_threshold    = 85
    mondoo_config_path = "${path.cwd}/scripts/mondoo.json"
  }
}
```

**Expected behavior**
Because the Asset name is being set uniquely, including timestamp, I would expect a new Asset to show up in Mondoo Inventory on each build. 

**Screenshots or CLI Output**
![image](https://github.com/mondoohq/packer-plugin-cnspec/assets/46723579/8c9a84a5-daa0-4e2a-aed7-a2e9e92acb94)
![image](https://github.com/mondoohq/packer-plugin-cnspec/assets/46723579/acce079d-1415-42dc-a9ab-3fa494db79dc)
![image](https://github.com/mondoohq/packer-plugin-cnspec/assets/46723579/2ae0b03c-0e9c-4d45-8f7a-51fe42d196f9)
![image](https://github.com/mondoohq/packer-plugin-cnspec/assets/46723579/58239f2e-4281-421a-acc4-674547987236)

**Additional context**
Provisioner version 11.1.1

**Comment by chris-rock** [comment]
@Beeez Thank you for the report. We looked into the issue. Depending on the packer template the used hostname leads to the same asset. We plan improvements to handle this case better without users changing something, but for now the solution is to generate unique hostnames. https://github.com/mondoohq/packer-plugin-cnspec/pull/238 is a sample how to do that for rhel-based systems.

**Comment by Beeez** [comment]
@chris-rock Thanks for the reply. Looks like that was the issue - the actual hostname. Might be a good feature to override or add to documentation that the hostname identifies it rather than the asset name. 

Appreciate the assistance.
