### ISSUE TITLE
Errors with sshd.config.params checks

### ISSUE THREAD

**Issue by xrayj11** [mondoohq/packer-plugin-cnspec#247]
**Describe the bug**
When using the cnspec packer plugin, which loads the os provider, versions >11.0.2 error when checking any `sshd.config.params`.
This does not cause errors with the plugin or the packer run, but the mondoo console is displaying the following for all checks using `sshd.config.params`, when it previously displayed true/false values:
```
[Query Error]
1 error occurred:
	* not implemented
```
**To Reproduce**

1. Using cnspec plugin in a packer build (tested on cnspec 11.1.0 and 11.1.1)
2. Build for Rocky Linux using the proxmox or vsphere builder, packer hcl based on [this example](https://github.com/vmware-samples/packer-examples-for-vsphere/blob/develop/builds/linux/rocky/9/linux-rocky.pkr.hcl)  (issues noticed on both)
3. Allow the cnspec plugin to pull the [OS provider](https://releases.mondoo.com/providers/os/index.html) >11.0.2 (issues noticed on OS provider 11.0.4 and 11.1.1)
4. Have a policy assigned that uses `sshd.config.params` to check for compliance (mondoo-linux-security)
5. Review the plugin output or mondoo console to see the errors on SSH related policy checks

**Expected behavior**
The cnspec plugin should have no issue collecting info on `sshd.config.params` and reporting the results back to the mondoo console. Instead of seeing errors in the plugin output or mondoo console, you should see pass/fail statuses.

**Screenshots or CLI Output**
Attached output of two runs of the same packer build, one with the os provisioner on 11.0.2 where the sshd.config.params are collected, and one with the os provisioner on 11.1.1 where the sshd.config.params are not collected.
These builds are done on the same commit of the repo, no changes were made to the packer build HCL.
I removed irrelevant failed/passed checks that are working and match between the two logs, so you will only see the erroring checks.
[working run.txt](https://github.com/mondoohq/packer-plugin-cnspec/files/15228375/working.run.txt)
[issue_run.txt](https://github.com/mondoohq/packer-plugin-cnspec/files/15228377/issue_run.txt)

Here's what I see in the mondoo console for these checks that rely on sshd.config.params:
![2024-05-06-214939_hyprshot](https://github.com/mondoohq/packer-plugin-cnspec/assets/34223210/3ec24f8d-a351-4a66-b2ec-ff7e9a1e583b)

**Desktop (please complete the following information):**

- OS: Proxmox / vCenter /(packer alpine docker container)
- OS Version: 8.2.2 / 7.0.3 /(packer alpine 1.10.2)

**Additional context**
I believe this to be an issue with the OS provider on mondoo's side given the issue is happening across cnspec versions, packer builders, hypervisors, with the only variable being the OS provider version.

**Comment by chris-rock** [comment]
@xrayj11 Thank you for the extensive report. If I understand the issue correctly:

- the ssh config does not include the the config for `LoginGraceTime`
- so the test is expected to fail
- the UI does not show the failure as it should be displayed

**Comment by xrayj11** [comment]
@chris-rock Thanks for responding.
The issue is not just with `LoginGraceTime`, I only show that in the picture as an example. Any check that uses `sshd.config.params` is erroring, when it used to be pass/fail.
Regardless of whether `LoginGraceTime` or any other parameter cnspec is checking is defined in the sshd_config, it is erroring.
You can see from the working_run.txt and issue_run.txt that when the OS provider is collecting information about `sshd.config.params`, it says `Error: Not Implemented` for the erroring run, while the working run shows information gathered from the host.

I should add that mondoo released a new version of the os provider (11.1.2), however the cnspec plugin is still failing to retrieve the sshd config params info.
What is also interesting is that when using `cnspec shell` on the host cloned from the template I built in packer, retrieving `sshd.config.params` works just fine with the latest os provider (11.1.2):
```
cnspec> sshd.config.params
sshd.config.params: {
  AllowTcpForwarding: "no"
  AuthorizedKeysFile: ".ssh/authorized_keys"
  Banner: "/etc/issue.net"
  CASignatureAlgorithms: "ecdsa-sha2-nistp256,sk-ecdsa-sha2-nistp256@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519,sk-ssh-ed25519@openssh.com,rsa-sha2-256,rsa-sha2-512"
  ChallengeResponseAuthentication: "no"
  Ciphers: "aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr"
  ClientAliveCountMax: "0"
  ClientAliveInterval: "300"
  GSSAPIAuthentication: "yes"
  GSSAPICleanupCredentials: "no"
  GSSAPIKexAlgorithms: "gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-"
  HostKeyAlgorithms: "ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com"
  HostbasedAuthentication: "no"
  IgnoreRhosts: "yes"
  KexAlgorithms: "curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512"
  LogLevel: "INFO"
  LoginGraceTime: "60"
  MACs: "hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512"
  MaxAuthTries: "4"
  MaxSessions: "10"
  MaxStartups: "10:30:60"
  PasswordAuthentication: "no"
  PermitEmptyPasswords: "no"
  PermitRootLogin: "yes"
  PermitUserEnvironment: "no"
  PrintMotd: "no"
  PubkeyAcceptedAlgorithms: "ecdsa-sha2-nistp256,ecdsa-sha2-nistp256-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521,ecdsa-sha2-nistp521-cert-v01@openssh.com,ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512,rsa-sha2-512-cert-v01@openssh.com"
  RequiredRSASize: "2048"
  Subsystem: "sftp /usr/libexec/openssh/sftp-server"
  SyslogFacility: "AUTHPRIV"
  UsePAM: "yes"
  X11Forwarding: "no"
}
```

**Comment by xrayj11** [comment]
This issue is still occurring despite recent packer, packer-plugin-cnspec, and os provider updates.
I bumped my packer template to build from the new Rocky 9.4 ISO, and that has not made a difference either.
I would like to try manually pinning the os provider version to do additional testing, but I'm not exactly sure how that would be implemented. I'm thinking somewhere here the version could be defined?
https://github.com/mondoohq/packer-plugin-cnspec/blob/f28135a75218e31b1acd1f697fc26f44802a17c5/provisioner/provisioner.go#L548-L550

**Comment by chris-rock** [comment]
The root issue is tracked here https://github.com/mondoohq/cnquery/issues/4198

**Comment by chris-rock** [comment]
Once the next os provider is released, this issue is fixed.
