### ISSUE TITLE
Release process seems broken. No compiled Assets after version  v11.5.0

### ISSUE THREAD

**Issue by ceso** [mondoohq/packer-plugin-cnspec#268]
**What is not working as you expected it?**
Since version v11.5.0 of the Plugin, there are no compiled releases anymore. This makes it impossible to use this plugin's latest up-to-date version without manually installing it from the sources every time a new release is there.

**Where on the platform does it happen?**
N/A

**How do we replicate the issue?**
Go to https://github.com/mondoohq/packer-plugin-cnspec/releases, and look at the Assets section of every released version after v11.5.0. Every release used to have assets such as darwin_amd64.zip, darwin_arm64.zip, linux_386.zip, linux_amd64.zip, linux_arm.zip, linux_arm64.zip, windows_amd64.zip, windows_arm64.zip, etc, but since v11.6.0 there's only a Source Code .zip and a Source Code .tar.gz

**Expected behavior (i.e. solution)**
Compiled version of each release are published and is possible to use this Packer Plugin without the need to manually compile the sources.

**Other Comments**

**Comment by chris-rock** [comment]
@ceso Thank you for the report, we have a look.

**Comment by chris-rock** [comment]
@ceso We updated the release process. We did something wrong with our automation. Apologies. We updated the v11.7.3 release and it has all the binaries attached now: https://github.com/mondoohq/packer-plugin-cnspec/releases/tag/v11.7.3

**Comment by ceso** [comment]
Thanks for the quick reply !
