### ISSUE TITLE
mondoo not found in PATH with GitHub Action

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/packer-plugin-cnspec#29]
Testing the Packer Plugin Mondoo with v0.5.1 with GitHub Actions and the HashiCorp Packer Action, it seems `mondoo` cannot be found in PATH despite being installed on the runner.

## ERROR: mondoo executable not found in $PATH

```bash
2022/08/22 23:27:09 packer-provisioner-shell plugin: [INFO] RPC client: Communicator ended with: 0
2022/08/22 23:27:09 [INFO] (telemetry) ending shell
2022/08/22 23:27:09 [INFO] (telemetry) Starting provisioner mondoo
==> mondoo-ubuntu-2004-secure-base.amazon-ebs.ubuntu2004: Running Mondoo packer provisioner (Version: 0.5.1, Build: f71f26f)
==> mondoo-ubuntu-2004-secure-base.amazon-ebs.ubuntu2004: Executing Mondoo: [mondoo scan ssh ubuntu@100.24.19.36:22 --score-threshold 0]
==> mondoo-ubuntu-2004-secure-base.amazon-ebs.ubuntu2004: read |0: file already closed
==> mondoo-ubuntu-2004-secure-base.amazon-ebs.ubuntu2004: read |0: file already closed
==> mondoo-ubuntu-2004-secure-base.amazon-ebs.ubuntu2004: exec: "mondoo": executable file not found in $PATH
2022/08/22 23:27:09 [INFO] (telemetry) ending mondoo
```

## Mondoo Client installed and configured successfully in Github Runner

The GitHub workflow is configured to install and configure Mondoo Client as follows:

```yaml
      - name: Install Mondoo Client
        shell: bash
        run: |
            echo Installing Mondoo Client...
            echo ${{ secrets.MONDOO_SERVICE_ACCOUNT }} | base64 -d > mondoo.json
            curl -sSL https://mondoo.com/install.sh | bash
            mondoo status --config ${{ env.MONDOO_CONFIG_PATH }}
```

Running `mondoo status --config config.json` in the workflow returns the a successful status:

```bash
https://mondoo.com/docs/operating_systems/installation/registration/
→ loaded configuration from mondoo.json using source --config
→ Hostname:	REDACTED
→ IP:		10.1.1.27
→ Platform:	ubuntu
→ Release:	20.04
→ Time:		2022-08-22T23:25:39Z
→ Version:	6.11.1 (API Version: 6)
→ API ConnectionConfig:	https://us.api.mondoo.com/
→ API Status:	SERVING
→ API Time:	2022-08-22T23:25:40Z
→ API Version:	6
→ Space:	//captain.api.mondoo.app/spaces/REDACTED
→ Client:	no managed client
→ Service Account:	//agents.api.mondoo.app/spaces/REDACTED/serviceaccounts/REDACTED
→ client is registered
→ client authenticated successfully
```

**Comment by chris-rock** [comment]
Why packer is being used via the github action then packer runs in a container https://github.com/hashicorp/packer-github-actions/blob/master/action.yml#L26-L28. Therefore the mondoo binary that was previously installed is not detected because it is not part of the container where packer runs in.

**Comment by scottford-io** [comment]
@preslavgerchev Whenever possible, I think we should be trying to make Mondoo work with existing marketplace Actions. For example, the new [Mondoo Docker Image Action](https://github.com/mondoohq/actions/blob/main/docker-image/README.md) provides examples of using the Docker Buildx Action rather than us installing Docker onto a runner and then running `docker build .`. 

With this integration, HashiCorp already did amazing work to make Packer work with GH Actions, so no need to reinvent the wheel. @chris-rock and I have already discussed this, and we need to get to a place where users do not have to worry about installing Mondoo anywhere. We need the `plugin` to handle installing Mondoo if it is not there. It would be great if that were configurable as well so users can pin the version of `mondoo` as `latest` could break production pipelines.

**Comment by ksatirli** [comment]
For some context from the @hashicorp side (and as the original author of the GH Action): the current version of the Action uses a Dockerized `packer` binary, making it ~impossible~ unnecessarily hard to work with any external binaries.

We're in the process of rebuilding the action to be "just" a `setup-packer` action, that will work as we'd all expect it to.

Thank you for your patience ❤️

**Comment by scottford-io** [comment]
This was resolved with the addition of the [Packer GitHub Action](https://github.com/marketplace/actions/setup-hashicorp-packer) by @hashicorp as mentioned by @ksatirli but also with the `cnspec` provisioner and `MONDOO_CONFIG_BASE64`. 

An additional GH Action workflow example was added with https://github.com/mondoohq/packer-plugin-cnspec/pull/140
