### ISSUE TITLE
Docs: broken link to policy scoring url

### ISSUE THREAD

**Issue by drewmullen** [mondoohq/packer-plugin-cnspec#97]
on line: https://github.com/mondoohq/packer-plugin-cnspec/blob/main/README.md?plain=1#L59

the link to the policy scoring docs is broken (aka https://mondoo.com/docs/platform/policies/scoring/index.html)

<img width="752" alt="image" src="https://user-images.githubusercontent.com/3812162/230954819-4397ca0d-845b-4860-a6b7-adbb4ac0be95.png">

nbd just reporting for awareness

**Comment by misterpantz** [comment]
https://github.com/mondoohq/packer-plugin-cnspec/pull/99
