### ISSUE TITLE
Feature: Ability to write cnspec results to a file for pipeline artifacts

### ISSUE THREAD

**Issue by drewmullen** [mondoohq/packer-plugin-cnspec#98]
**Is your feature request related to a problem? Please describe.**
I'm trying to showcase how automated scanning can be done in pipelines. Mondoo saas is 1 option and it looks pretty great! However, its also possible to use the [CLI to produce outputs](https://mondoo.com/docs/cnspec/#create-a-json-report). It would be nice to have that as an option in packer.

The implementation may actually be a packer post_processor but im not a packer dev so im not completely sure...

```
  provisioner "cnspec" {
    on_failure      = "continue"
    score_threshold = 100
    output =  "json"
    output_file = "cnspec-test-results.json"
  }
```

OR

```
post_processor "cnspec-output" {
  output_file = "cnspec-test-results.json"
}
```

**Comment by chris-rock** [comment]
That is a great idea @drewmullen

**Comment by nywilken** [comment]
This branch probably needs some updating to work with the latest changes but I did start adding such a feature when I first tested the provisioner [here](https://github.com/nywilken/packer-plugin-cnspec/tree/add-output-file). Might thought process was to pair it up with the `artiface` post-processor to download the file from the remote instance as a separate artifact, which can then be used by the consumer. Just adding my vote fore the request 😄
